import { runScan } from './report.js';

/**
 * Entry point for the browser's "Run inspection" flow — bundled into
 * public/scan.mjs at build time (see the build:scan npm script) and
 * executed by the downloadable .command file the dashboard generates
 * (see src/components/ScanModal.tsx). Unlike cli.ts this is meant for
 * people who have never opened a terminal: no flags to learn, no login
 * step — it scans, uploads with the embedded one-time token, and tells
 * the user to go back to their browser.
 *
 * Same privacy contract as every other path: metadata only, and the
 * upload happens because the user explicitly clicked "Run inspection"
 * in the dashboard and opened the file it gave them.
 */
function arg(name: string): string {
  const i = process.argv.indexOf(`--${name}`);
  const value = i >= 0 ? process.argv[i + 1] : undefined;
  if (!value) {
    console.error(`Missing --${name}. This file is generated by the AI Check dashboard — please download a fresh one.`);
    process.exit(1);
  }
  return value;
}

async function main() {
  const api = arg('api');
  const token = arg('token');

  console.log('AI Check is scanning your Mac — this looks at folder sizes only, never inside your files.');
  console.log('This usually takes under a minute...\n');

  const report = await runScan();

  const gb = (b: number) => (b / 1024 ** 3).toFixed(1) + ' GB';
  console.log(`Disk: ${gb(report.storage.usedBytes)} used of ${gb(report.storage.totalBytes)}`);
  console.log(`Safe to clean up: ${gb(report.storage.reclaimableBytes)}\n`);

  console.log('Sending the results to your dashboard...');
  const res = await fetch(`${api}/api/v1/report`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Scan-Token': token },
    body: JSON.stringify(report),
  });

  if (!res.ok) {
    const body = (await res.json().catch(() => null)) as { error?: { message?: string } } | null;
    console.error(`\nCould not send the results: ${body?.error?.message ?? `server responded with ${res.status}`}`);
    console.error('Go back to your browser and click "Run inspection" again to get a fresh scan file.');
    process.exit(1);
  }

  console.log('\n✅ All done! Go back to your browser — your results are ready.');
  console.log('You can close this window now.');
}

main().catch((error) => {
  console.error('\nThe scan hit a problem:', error instanceof Error ? error.message : error);
  console.error('Go back to your browser and try "Run inspection" again.');
  process.exit(1);
});
