import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, Download, Loader2, MousePointerClick, X } from 'lucide-react';
import { apiFetch } from '../lib/apiFetch';

/**
 * The guided "Run inspection" flow — written for someone who has never
 * opened a terminal. Mints a one-time scan token (POST /api/v1/scan-token),
 * generates a double-clickable .command file with the token inlined, then
 * polls the report list until the upload lands and celebrates.
 *
 * Only meaningful in cloud-api mode; mock/local-report builds show the
 * developer instructions instead (see the isCloudApi branch below).
 */

interface ReportSummary {
  id: string;
}

function scanScript(origin: string, token: string): string {
  // A plain shell script kept deliberately boring: find (or fetch a
  // portable) Node, download the freshly-deployed scanner bundle from
  // this same origin, run it with the one-time token. Everything lands
  // in ~/Library/Application Support/AICheck, nothing touches the rest
  // of the system.
  return `#!/bin/bash
# AI Check — one-click device scan
# Generated by ${origin} — safe to delete after use (the code inside
# only reads folder sizes, never your files' contents).
set -e
clear 2>/dev/null || true
echo "  ╭──────────────────────────────────────╮"
echo "  │   AI Check — scanning your Mac       │"
echo "  ╰──────────────────────────────────────╯"
echo
API="${origin}"
DIR="$HOME/Library/Application Support/AICheck"
mkdir -p "$DIR"

NODE="$(command -v node || true)"
if [ -z "$NODE" ]; then
  NV="v20.18.1"
  case "$(uname -m)" in
    arm64) NARCH="darwin-arm64" ;;
    *) NARCH="darwin-x64" ;;
  esac
  NODE="$DIR/node-$NV-$NARCH/bin/node"
  if [ ! -x "$NODE" ]; then
    echo "First run: downloading a small helper (about 40 MB, one time only)..."
    curl -fsSL "https://nodejs.org/dist/$NV/node-$NV-$NARCH.tar.gz" | tar -xz -C "$DIR"
  fi
fi

curl -fsSL "$API/scan.mjs" -o "$DIR/scan.mjs"
"$NODE" "$DIR/scan.mjs" --api "$API" --token "${token}"
echo
read -p "Press Enter to close this window..." _ 2>/dev/null || true
`;
}

export function ScanModal({ onClose, onComplete }: { onClose: () => void; onComplete: () => void }) {
  const isCloudApi = import.meta.env.VITE_PROVIDER_MODE === 'cloud-api';
  const [phase, setPhase] = useState<'intro' | 'waiting' | 'done' | 'error'>('intro');
  const [error, setError] = useState<string | null>(null);
  const baselineIds = useRef<Set<string>>(new Set());

  // While waiting, poll the report list every 5s for an id we haven't
  // seen — that's the scan the user just ran landing on the server.
  useEffect(() => {
    if (phase !== 'waiting') return;
    const timer = setInterval(async () => {
      try {
        const reports = await apiFetch<ReportSummary[]>('/api/v1/report/history');
        if (reports.some((r) => !baselineIds.current.has(r.id))) setPhase('done');
      } catch {
        // Transient poll failure — keep waiting; the next tick retries.
      }
    }, 5000);
    return () => clearInterval(timer);
  }, [phase]);

  async function downloadScanFile() {
    setError(null);
    try {
      const reports = await apiFetch<ReportSummary[]>('/api/v1/report/history').catch(() => [] as ReportSummary[]);
      baselineIds.current = new Set(reports.map((r) => r.id));

      const { token } = await apiFetch<{ token: string }>('/api/v1/scan-token', { method: 'POST' });
      const blob = new Blob([scanScript(window.location.origin, token)], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'AI-Check-Scan.command';
      a.click();
      URL.revokeObjectURL(url);
      setPhase('waiting');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not prepare the scan. Please try again.');
      setPhase('error');
    }
  }

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose} aria-label="Close">
          <X size={18} />
        </button>

        {!isCloudApi ? (
          <>
            <h2>Run an inspection</h2>
            <p className="modal-copy">
              This build reads scans from your local machine. Open a terminal in the project folder and run{' '}
              <code>npm run scan</code>, then refresh this page to see the results.
            </p>
          </>
        ) : phase === 'done' ? (
          <div className="modal-center">
            <CheckCircle2 size={44} className="modal-success" />
            <h2>Scan complete!</h2>
            <p className="modal-copy">Your results are ready. Let's take a look.</p>
            <button className="button primary" onClick={onComplete}>
              See my results
            </button>
          </div>
        ) : phase === 'waiting' ? (
          <div className="modal-center">
            <Loader2 size={36} className="modal-spinner" />
            <h2>Waiting for your scan...</h2>
            <p className="modal-copy">
              Open the <b>AI-Check-Scan.command</b> file in your <b>Downloads</b> folder — double-click it and a window
              will do everything for you. Results appear here automatically when it finishes.
            </p>
            <p className="modal-hint">
              If your Mac says the file "cannot be opened": right-click (or hold Control and click) the file, choose{' '}
              <b>Open</b>, then click <b>Open</b> again. You only have to do this once.
            </p>
            <button className="ghost" onClick={downloadScanFile}>
              Didn't get the file? Download it again
            </button>
          </div>
        ) : (
          <>
            <h2>Scan this Mac</h2>
            <p className="modal-copy">Three easy steps — no technical knowledge needed, and it takes about a minute.</p>
            <ol className="modal-steps">
              <li>
                <span className="modal-step-icon">
                  <Download size={16} />
                </span>
                <span>
                  <b>Download the scan file</b>
                  <small>Click the button below — a small file lands in your Downloads folder.</small>
                </span>
              </li>
              <li>
                <span className="modal-step-icon">
                  <MousePointerClick size={16} />
                </span>
                <span>
                  <b>Double-click the file</b>
                  <small>A window opens and scans on its own. It only looks at folder sizes — never inside your files.</small>
                </span>
              </li>
              <li>
                <span className="modal-step-icon">
                  <CheckCircle2 size={16} />
                </span>
                <span>
                  <b>Come back here</b>
                  <small>Your results show up on this page automatically.</small>
                </span>
              </li>
            </ol>
            {error && <p className="login-error">{error}</p>}
            <button className="button primary modal-cta" onClick={downloadScanFile}>
              <Download size={15} /> Download scan file
            </button>
          </>
        )}
      </div>
    </div>
  );
}
